### PR TITLE
CAP service to mock the Northwind Product service

### PR DESCRIPTION
**Pull request by sbarzaghialteaup**
I'm pleasure to share this CAP service we used to try the managed-html5-runtime-fiori-mta app with a CAP service requiring authentication, more info in readme.

### CODE REVIEW

**Comment by IObert** [comment]
Hi,

first of all, thanks a lot for your contribution!
I like the code and the project but I have to admit that I don't quite see how this CAP app fits in the context of general "html5-apps-samples". Could you please explain your motivation for this PR?

Please don't get this wrong, I would like to merge it but I also want to make sure it aligns as good as possible with the other samples included in the mono repo. Is this PR maybe related to #27 or do you think you could adapt it to address the issue?

**Comment by sbarzaghialteaup** [comment]
Hi,

I will not get it wrong, don't be afraid, whatever your choice is I will create further PR in the future anyway ;-)

I was looking for a sample like the managed-html-runtime-fiori-mta but with a CAP service with authentication as backend, I couldn't find anything and so I created this one.
I like the idea to address this requirement without changing anything in the original managed-html-runtime-fiori-mta project, only changes to the destination are necessary.

Inside the mono repo is like a sidecar/utility project.

Maybe this idea can be completed adding a reference to this CAP app into the original managed-html-runtime-fiori-mta samples, something like:
"This sample use the Northwind odata.org service, to use a CAP service as backend service look to the cap-service folder"

About #27, the request seems to be to have a single MTA with frontend and backend, this PR is for a separate MTA for the backend service.
However I can create a specific folder like ''managed-html5-runtime-fiori-cap-mta" with a single MTA with both frontend and backend, let me know.

Ciao
Sam

**Comment by IObert** [comment]
Ok, I got it. Yes, I think it would be great to have such an example (also if it's "backend only"). For this, I would like to ask you to make the following changes:
* Polish the `cap-service/readme.md` a bit to explain the purpose of this module
* Add a short explanation of this folder in the main readme as well
* Adapt the `cap-service/mta.yaml` to override any "Northwind" destination with the right URL and the needed props to avoid manual editing. The discussion of #27 contains the needed lines.
* Rename the folder from "cap-service" to "optional-self-hosted-backend" (or similar) to clearly indicate what it is
* Add a markdown note (">") in the respective sample readme (`managed-html-runtime-fiori-mta/readme.md`) to hint users to this option
Please let me know if you have any open questions. I'd be happy to help

**Comment by sbarzaghialteaup** [comment]
Hi, fine, I will send you the changes ciao

**Comment by sbarzaghialteaup** [comment]
Work done, let me know if somethings need to be changed.

**Comment by IObert** [comment]
Looks good to me, thanks for your contribution :)

**Pull request merged**
